### ISSUE TITLE
Unable to send empty (NULL) payload message 

### ISSUE THREAD

**Issue by acefed** [nosybore/Tasker-MQTT-Publish-Plugin#7]
In order to remove an old obsolete retained message on a mosquitto broker, I tried to send a new retained message with an empty (NULL) payload to the topic in case, as was suggested on the mosquitto mailinglist.

Sending this message with a mosquitto_pub client works as intended and removes the retained message from the topic.
Sending this message with the Tasker MQTT Publisher plugin is not possible, I assume some validation rule (payload not empty) prevents this.

I think fixing/changing this would improve the plugin, making MQTT more "payload agnostic" and introducing the support of retained message removal this way.

Tested today on Nexus 5 / Android 5.1.1 / Tasker 4.7u2 / MPP 1.2.0 and a Mosquitto broker.

PS: Many thanks for this excellent and otherwise flawless plugin!
I added it to the Tasker wiki on http://tasker.wikidot.com/plug-ins-and-3rd-party
...and hope you don't mind. If so, let me know and I remove it again.

**Comment by nosybore** [comment]
Yeah, this sounds fixable - once I can find some time to devote to this again.

**Comment by acefed** [comment]
Not sure what changed where when, but (null) payloads seem to work ok now, despite the Play Store description stating otherwise.

Tested on Samsung Galaxy S6, Android 7.0, Tasker v5.0u4, MQTT Publisher Plugin v1.4.0
